image: ubuntu
platform: Any CPU

environment:
  CODACY_PROJECT_TOKEN:
    secure: SoSYUwJEpz+Bt/ncgS8wbDn8lfZC9+N7h8JRfvIy5nnvIVQ4mopljMZe0uWE6TLJ
  CC_TEST_REPORTER_ID:
    secure: vjiUk28iFY0sxsFHuhz9+tPt5aI/IRPhHX/Mlehq9xqxG3RxO4wiKLlYQaK38hFwnZ3osTQnFGlCgI0tKleg4QJ46AiMRsl1z6t3v12OZvs=

stack: "node 14"

install:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # install modules
  - sh: npm ci
  - sh: npm install -g mocha c8

before_test:
  # Download codeclimate test report
  - sh: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./codeclimate-test-reporter
  - sh: chmod +x ./codeclimate-test-reporter

test_script:
  - c8 --reporter=lcov mocha

after_test:
  # Send test result to codeclimate
  - sh: ./codeclimate-test-reporter before-build
  - sh: ./codeclimate-test-reporter after-build -t lcov --exit-code $?
  # Send test result to Codacy
  - sh: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ./coverage/lcov.info

# Don't actually build.
build: off
